---
language: ruby
sudo: false
cache: bundler
branches:
  only:
  - master
  - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
before_install:
  - gem update --system
  - echo "gem: --no-document" > $HOME/.gemrc
  - gem install bundler
dist: trusty
rvm:
  - 2.6.0
script: bundle exec rake test
