# Site settings
title: Protokoll
author: Hemtjänst
description: Protocol documentation
baseurl: "/protokoll"
url: "https://hemtjan.st"
repository: "hemtjanst/protokoll"

# Build settings
theme: just-the-docs
remote_theme: pmarsceill/just-the-docs
search_enabled: true
aux_links:
    "Hemtjänst":
      - "https://hemtjan.st"
    "GitHub":
      - "https://github.com/hemtjanst"
markdown: kramdown
encoding: utf-8
timezone: Etc/UTC
permalink: pretty
kramdown:
 input: GFM
 hard_wrap: false
 math_engine: mathjax
 syntax_highlighter: rouge
future: true
jailed: false
gfm_quirks: paragraph_end
lsi: false
safe: true
markdown: kramdown
highlighter: rouge
gist:
 noscript: false

exclude: ["Gemfile", "Gemfile.lock", "LICENSE", "CNAME", "README.md", "vendor"]

plugins:
  - jemoji
  - jekyll-seo-tag
  - jekyll-sitemap

whitelist:
  - jemoji
  - jekyll-seo-tag
  - jekyll-sitemap
